# Example .promptbuilder.yaml configuration file

# default_meta_prompt_template_path: /path/to/your/custom/template.j2 # Optional override
placeholder_format: "__%s__"
context_max_file_size_mb: 0.3
context_supported_extensions:
  - .py
  - .md
  - .txt
  - .rst
context_encoding: utf-8
copy_to_clipboard_default: true
output_dir: ./generated_prompts
interactive_multiline_end_marker: EOD # End Of Document